// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using RequestService.Infrastructure.Persistence;

namespace RequestService.WebApi.Migrations
{
    [DbContext (typeof (RequestServiceDbContext))]
    [Migration ("20190314123027_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel (ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation ("Relational:MaxIdentifierLength", 128)
                .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity ("RequestService.WebApi.Domain.Requests.Answer", b =>
            {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int> ("RequestId");

                b.Property<string> ("TextTranslated");

                b.HasKey ("Id");

                b.HasIndex ("RequestId");

                b.ToTable ("Answer");
            });

            modelBuilder.Entity ("RequestService.WebApi.Domain.Requests.Request", b =>
            {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnName ("RequestID")
                    .HasAnnotation ("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string> ("LanguageOrigin");

                b.Property<string> ("LanguageTarget")
                    .IsRequired ();

                b.Property<string> ("TextToTranslate")
                    .IsRequired ();

                b.HasKey ("Id");

                b.ToTable ("Requests");
            });

            modelBuilder.Entity ("RequestService.WebApi.Domain.Requests.Answer", b =>
            {
                b.HasOne ("RequestService.WebApi.Domain.Requests.Request")
                    .WithMany ("Answers")
                    .HasForeignKey ("RequestId")
                    .OnDelete (DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}